name: "Azure Storage Firewall Default Action"
author: "Jesse Loudon <loudoninbox@outlook.com>"
description: Configures Azure Storage Firewall's Default Action to "Allow" or "Deny" access. Useful to run before or after Storage actions.
branding:
  icon: "shield"
  color: "blue"
inputs:
  sp_client_id:
    description: Service Principal Client ID
    required: true
  sp_client_secret:
    description: Service Principal Client Secret   
    required: true
  tenant_id:
    description: Azure Tenant ID where the SP is created
    required: true
  resourcegroup_name:
    description: Resource Group name containing the Storage Account
    required: true
  storageaccount_name:
    description: Storage Account name to configure
    required: true
  configure_firewall_default_action:
    description: Default Action to set either Allow or Deny
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
